name: "Rickroll"
description: "Lien caché vers le score de mutation (Rickroll)"

runs:
  using: "composite"
  steps:
    - name: Affichage du lien Rickroll
      shell: bash
      run: |
        # Affiche le lien en Markdown dans les logs
        echo "[Regarder le score de mutation](https://www.youtube.com/watch?v=dQw4w9WgXcQ)"

      
