name: "Rickroll"
description: "Lien caché vers le score de mutation (Rickroll)"

runs:
  using: "composite"
  steps:
    - name: Rickroll link
      shell: bash
      run: |
        # Affichage dans les logs
        echo "[résultats des tests de mutations](https://www.youtube.com/watch?v=dQw4w9WgXcQ)"


      
